### ISSUE TITLE
Déjà implémenté

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/plugin-ecodevicegce#1]
https://github.com/guenneguezt/plugin-ecodevice

**Comment by sarakha63** [comment]
Oui cela nempeche pas une deuxième implementation

**Comment by guenneguezt** [comment]
C'est juste que je trouve cela dommage surtout que le plugin existant est gratuit et maintenu.
En plus, j'ai l'impression d'être plutôt ouvert aux remarques.
Après aucun souci, mais j'ai l'impression qu'il y a d'autres priorités.

**Comment by sarakha63** [comment]
Cest juste un projet sur temps libre donc mange pas de pain.  Et le fait quil soit gratuit a facilité le choix sinon je me serais pas permis. Rien ne dit quil verra le jour
